/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_phidgets_AdvancedServoPhidget */

#ifndef _Included_com_phidgets_AdvancedServoPhidget
#define _Included_com_phidgets_AdvancedServoPhidget
#ifdef __cplusplus
extern "C" {
#endif
#undef com_phidgets_AdvancedServoPhidget_PHIDGET_LOG_CRITICAL
#define com_phidgets_AdvancedServoPhidget_PHIDGET_LOG_CRITICAL 1L
#undef com_phidgets_AdvancedServoPhidget_PHIDGET_LOG_ERROR
#define com_phidgets_AdvancedServoPhidget_PHIDGET_LOG_ERROR 2L
#undef com_phidgets_AdvancedServoPhidget_PHIDGET_LOG_WARNING
#define com_phidgets_AdvancedServoPhidget_PHIDGET_LOG_WARNING 3L
#undef com_phidgets_AdvancedServoPhidget_PHIDGET_LOG_DEBUG
#define com_phidgets_AdvancedServoPhidget_PHIDGET_LOG_DEBUG 4L
#undef com_phidgets_AdvancedServoPhidget_PHIDGET_LOG_INFO
#define com_phidgets_AdvancedServoPhidget_PHIDGET_LOG_INFO 5L
#undef com_phidgets_AdvancedServoPhidget_PHIDGET_LOG_VERBOSE
#define com_phidgets_AdvancedServoPhidget_PHIDGET_LOG_VERBOSE 6L
/*
 * Class:     com_phidgets_AdvancedServoPhidget
 * Method:    create
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_phidgets_AdvancedServoPhidget_create
  (JNIEnv *, jclass);

/*
 * Class:     com_phidgets_AdvancedServoPhidget
 * Method:    getMotorCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_phidgets_AdvancedServoPhidget_getMotorCount
  (JNIEnv *, jobject);

/*
 * Class:     com_phidgets_AdvancedServoPhidget
 * Method:    getAccelerationMax
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_com_phidgets_AdvancedServoPhidget_getAccelerationMax
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_phidgets_AdvancedServoPhidget
 * Method:    getAccelerationMin
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_com_phidgets_AdvancedServoPhidget_getAccelerationMin
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_phidgets_AdvancedServoPhidget
 * Method:    getVelocityMax
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_com_phidgets_AdvancedServoPhidget_getVelocityMax
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_phidgets_AdvancedServoPhidget
 * Method:    getVelocityMin
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_com_phidgets_AdvancedServoPhidget_getVelocityMin
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_phidgets_AdvancedServoPhidget
 * Method:    getPositionMax
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_com_phidgets_AdvancedServoPhidget_getPositionMax
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_phidgets_AdvancedServoPhidget
 * Method:    setPositionMax
 * Signature: (ID)V
 */
JNIEXPORT void JNICALL Java_com_phidgets_AdvancedServoPhidget_setPositionMax
  (JNIEnv *, jobject, jint, jdouble);

/*
 * Class:     com_phidgets_AdvancedServoPhidget
 * Method:    getPositionMin
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_com_phidgets_AdvancedServoPhidget_getPositionMin
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_phidgets_AdvancedServoPhidget
 * Method:    setPositionMin
 * Signature: (ID)V
 */
JNIEXPORT void JNICALL Java_com_phidgets_AdvancedServoPhidget_setPositionMin
  (JNIEnv *, jobject, jint, jdouble);

/*
 * Class:     com_phidgets_AdvancedServoPhidget
 * Method:    getAcceleration
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_com_phidgets_AdvancedServoPhidget_getAcceleration
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_phidgets_AdvancedServoPhidget
 * Method:    setAcceleration
 * Signature: (ID)V
 */
JNIEXPORT void JNICALL Java_com_phidgets_AdvancedServoPhidget_setAcceleration
  (JNIEnv *, jobject, jint, jdouble);

/*
 * Class:     com_phidgets_AdvancedServoPhidget
 * Method:    getVelocityLimit
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_com_phidgets_AdvancedServoPhidget_getVelocityLimit
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_phidgets_AdvancedServoPhidget
 * Method:    setVelocityLimit
 * Signature: (ID)V
 */
JNIEXPORT void JNICALL Java_com_phidgets_AdvancedServoPhidget_setVelocityLimit
  (JNIEnv *, jobject, jint, jdouble);

/*
 * Class:     com_phidgets_AdvancedServoPhidget
 * Method:    getVelocity
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_com_phidgets_AdvancedServoPhidget_getVelocity
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_phidgets_AdvancedServoPhidget
 * Method:    getPosition
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_com_phidgets_AdvancedServoPhidget_getPosition
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_phidgets_AdvancedServoPhidget
 * Method:    setPosition
 * Signature: (ID)V
 */
JNIEXPORT void JNICALL Java_com_phidgets_AdvancedServoPhidget_setPosition
  (JNIEnv *, jobject, jint, jdouble);

/*
 * Class:     com_phidgets_AdvancedServoPhidget
 * Method:    getEngaged
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_phidgets_AdvancedServoPhidget_getEngaged
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_phidgets_AdvancedServoPhidget
 * Method:    setEngaged
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_com_phidgets_AdvancedServoPhidget_setEngaged
  (JNIEnv *, jobject, jint, jboolean);

/*
 * Class:     com_phidgets_AdvancedServoPhidget
 * Method:    getSpeedRampingOn
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_phidgets_AdvancedServoPhidget_getSpeedRampingOn
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_phidgets_AdvancedServoPhidget
 * Method:    setSpeedRampingOn
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_com_phidgets_AdvancedServoPhidget_setSpeedRampingOn
  (JNIEnv *, jobject, jint, jboolean);

/*
 * Class:     com_phidgets_AdvancedServoPhidget
 * Method:    getCurrent
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_com_phidgets_AdvancedServoPhidget_getCurrent
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_phidgets_AdvancedServoPhidget
 * Method:    getStopped
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_phidgets_AdvancedServoPhidget_getStopped
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_phidgets_AdvancedServoPhidget
 * Method:    enableServoPositionChangeEvents
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_phidgets_AdvancedServoPhidget_enableServoPositionChangeEvents
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_phidgets_AdvancedServoPhidget
 * Method:    enableServoVelocityChangeEvents
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_phidgets_AdvancedServoPhidget_enableServoVelocityChangeEvents
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_phidgets_AdvancedServoPhidget
 * Method:    enableCurrentChangeEvents
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_phidgets_AdvancedServoPhidget_enableCurrentChangeEvents
  (JNIEnv *, jobject, jboolean);

#ifdef __cplusplus
}
#endif
#endif
