/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_phidgets_WeightSensorPhidget */

#ifndef _Included_com_phidgets_WeightSensorPhidget
#define _Included_com_phidgets_WeightSensorPhidget
#ifdef __cplusplus
extern "C" {
#endif
#undef com_phidgets_WeightSensorPhidget_PHIDGET_LOG_CRITICAL
#define com_phidgets_WeightSensorPhidget_PHIDGET_LOG_CRITICAL 1L
#undef com_phidgets_WeightSensorPhidget_PHIDGET_LOG_ERROR
#define com_phidgets_WeightSensorPhidget_PHIDGET_LOG_ERROR 2L
#undef com_phidgets_WeightSensorPhidget_PHIDGET_LOG_WARNING
#define com_phidgets_WeightSensorPhidget_PHIDGET_LOG_WARNING 3L
#undef com_phidgets_WeightSensorPhidget_PHIDGET_LOG_DEBUG
#define com_phidgets_WeightSensorPhidget_PHIDGET_LOG_DEBUG 4L
#undef com_phidgets_WeightSensorPhidget_PHIDGET_LOG_INFO
#define com_phidgets_WeightSensorPhidget_PHIDGET_LOG_INFO 5L
#undef com_phidgets_WeightSensorPhidget_PHIDGET_LOG_VERBOSE
#define com_phidgets_WeightSensorPhidget_PHIDGET_LOG_VERBOSE 6L
/*
 * Class:     com_phidgets_WeightSensorPhidget
 * Method:    create
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_phidgets_WeightSensorPhidget_create
  (JNIEnv *, jclass);

/*
 * Class:     com_phidgets_WeightSensorPhidget
 * Method:    getWeight
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_com_phidgets_WeightSensorPhidget_getWeight
  (JNIEnv *, jobject);

/*
 * Class:     com_phidgets_WeightSensorPhidget
 * Method:    setWeightChangeTrigger
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_com_phidgets_WeightSensorPhidget_setWeightChangeTrigger
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     com_phidgets_WeightSensorPhidget
 * Method:    getWeightChangeTrigger
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_com_phidgets_WeightSensorPhidget_getWeightChangeTrigger
  (JNIEnv *, jobject);

/*
 * Class:     com_phidgets_WeightSensorPhidget
 * Method:    enableWeightChangeEvents
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_phidgets_WeightSensorPhidget_enableWeightChangeEvents
  (JNIEnv *, jobject, jboolean);

#ifdef __cplusplus
}
#endif
#endif
