/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_phidgets_TextLEDPhidget */

#ifndef _Included_com_phidgets_TextLEDPhidget
#define _Included_com_phidgets_TextLEDPhidget
#ifdef __cplusplus
extern "C" {
#endif
#undef com_phidgets_TextLEDPhidget_PHIDGET_LOG_CRITICAL
#define com_phidgets_TextLEDPhidget_PHIDGET_LOG_CRITICAL 1L
#undef com_phidgets_TextLEDPhidget_PHIDGET_LOG_ERROR
#define com_phidgets_TextLEDPhidget_PHIDGET_LOG_ERROR 2L
#undef com_phidgets_TextLEDPhidget_PHIDGET_LOG_WARNING
#define com_phidgets_TextLEDPhidget_PHIDGET_LOG_WARNING 3L
#undef com_phidgets_TextLEDPhidget_PHIDGET_LOG_DEBUG
#define com_phidgets_TextLEDPhidget_PHIDGET_LOG_DEBUG 4L
#undef com_phidgets_TextLEDPhidget_PHIDGET_LOG_INFO
#define com_phidgets_TextLEDPhidget_PHIDGET_LOG_INFO 5L
#undef com_phidgets_TextLEDPhidget_PHIDGET_LOG_VERBOSE
#define com_phidgets_TextLEDPhidget_PHIDGET_LOG_VERBOSE 6L
/*
 * Class:     com_phidgets_TextLEDPhidget
 * Method:    create
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_phidgets_TextLEDPhidget_create
  (JNIEnv *, jclass);

/*
 * Class:     com_phidgets_TextLEDPhidget
 * Method:    getRowCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_phidgets_TextLEDPhidget_getRowCount
  (JNIEnv *, jobject);

/*
 * Class:     com_phidgets_TextLEDPhidget
 * Method:    getColumnCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_phidgets_TextLEDPhidget_getColumnCount
  (JNIEnv *, jobject);

/*
 * Class:     com_phidgets_TextLEDPhidget
 * Method:    getBrightness
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_phidgets_TextLEDPhidget_getBrightness
  (JNIEnv *, jobject);

/*
 * Class:     com_phidgets_TextLEDPhidget
 * Method:    setBrightness
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_phidgets_TextLEDPhidget_setBrightness
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_phidgets_TextLEDPhidget
 * Method:    setDisplayString
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_phidgets_TextLEDPhidget_setDisplayString
  (JNIEnv *, jobject, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
