/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_phidgets_ServoPhidget */

#ifndef _Included_com_phidgets_ServoPhidget
#define _Included_com_phidgets_ServoPhidget
#ifdef __cplusplus
extern "C" {
#endif
#undef com_phidgets_ServoPhidget_PHIDGET_LOG_CRITICAL
#define com_phidgets_ServoPhidget_PHIDGET_LOG_CRITICAL 1L
#undef com_phidgets_ServoPhidget_PHIDGET_LOG_ERROR
#define com_phidgets_ServoPhidget_PHIDGET_LOG_ERROR 2L
#undef com_phidgets_ServoPhidget_PHIDGET_LOG_WARNING
#define com_phidgets_ServoPhidget_PHIDGET_LOG_WARNING 3L
#undef com_phidgets_ServoPhidget_PHIDGET_LOG_DEBUG
#define com_phidgets_ServoPhidget_PHIDGET_LOG_DEBUG 4L
#undef com_phidgets_ServoPhidget_PHIDGET_LOG_INFO
#define com_phidgets_ServoPhidget_PHIDGET_LOG_INFO 5L
#undef com_phidgets_ServoPhidget_PHIDGET_LOG_VERBOSE
#define com_phidgets_ServoPhidget_PHIDGET_LOG_VERBOSE 6L
/*
 * Class:     com_phidgets_ServoPhidget
 * Method:    create
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_phidgets_ServoPhidget_create
  (JNIEnv *, jclass);

/*
 * Class:     com_phidgets_ServoPhidget
 * Method:    getMotorCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_phidgets_ServoPhidget_getMotorCount
  (JNIEnv *, jobject);

/*
 * Class:     com_phidgets_ServoPhidget
 * Method:    getPosition
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_com_phidgets_ServoPhidget_getPosition
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_phidgets_ServoPhidget
 * Method:    getPositionMax
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_com_phidgets_ServoPhidget_getPositionMax
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_phidgets_ServoPhidget
 * Method:    getPositionMin
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_com_phidgets_ServoPhidget_getPositionMin
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_phidgets_ServoPhidget
 * Method:    setPosition
 * Signature: (ID)V
 */
JNIEXPORT void JNICALL Java_com_phidgets_ServoPhidget_setPosition
  (JNIEnv *, jobject, jint, jdouble);

/*
 * Class:     com_phidgets_ServoPhidget
 * Method:    setEngaged
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_com_phidgets_ServoPhidget_setEngaged
  (JNIEnv *, jobject, jint, jboolean);

/*
 * Class:     com_phidgets_ServoPhidget
 * Method:    setMotorOn
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_com_phidgets_ServoPhidget_setMotorOn
  (JNIEnv *, jobject, jint, jboolean);

/*
 * Class:     com_phidgets_ServoPhidget
 * Method:    getEngaged
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_phidgets_ServoPhidget_getEngaged
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_phidgets_ServoPhidget
 * Method:    getMotorOn
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_phidgets_ServoPhidget_getMotorOn
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_phidgets_ServoPhidget
 * Method:    enableServoPositionChangeEvents
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_phidgets_ServoPhidget_enableServoPositionChangeEvents
  (JNIEnv *, jobject, jboolean);

#ifdef __cplusplus
}
#endif
#endif
