/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_phidgets_TemperatureSensorPhidget */

#ifndef _Included_com_phidgets_TemperatureSensorPhidget
#define _Included_com_phidgets_TemperatureSensorPhidget
#ifdef __cplusplus
extern "C" {
#endif
#undef com_phidgets_TemperatureSensorPhidget_PHIDGET_LOG_CRITICAL
#define com_phidgets_TemperatureSensorPhidget_PHIDGET_LOG_CRITICAL 1L
#undef com_phidgets_TemperatureSensorPhidget_PHIDGET_LOG_ERROR
#define com_phidgets_TemperatureSensorPhidget_PHIDGET_LOG_ERROR 2L
#undef com_phidgets_TemperatureSensorPhidget_PHIDGET_LOG_WARNING
#define com_phidgets_TemperatureSensorPhidget_PHIDGET_LOG_WARNING 3L
#undef com_phidgets_TemperatureSensorPhidget_PHIDGET_LOG_DEBUG
#define com_phidgets_TemperatureSensorPhidget_PHIDGET_LOG_DEBUG 4L
#undef com_phidgets_TemperatureSensorPhidget_PHIDGET_LOG_INFO
#define com_phidgets_TemperatureSensorPhidget_PHIDGET_LOG_INFO 5L
#undef com_phidgets_TemperatureSensorPhidget_PHIDGET_LOG_VERBOSE
#define com_phidgets_TemperatureSensorPhidget_PHIDGET_LOG_VERBOSE 6L
#undef com_phidgets_TemperatureSensorPhidget_PHIDGET_TEMPERATURE_SENSOR_K_TYPE
#define com_phidgets_TemperatureSensorPhidget_PHIDGET_TEMPERATURE_SENSOR_K_TYPE 1L
#undef com_phidgets_TemperatureSensorPhidget_PHIDGET_TEMPERATURE_SENSOR_J_TYPE
#define com_phidgets_TemperatureSensorPhidget_PHIDGET_TEMPERATURE_SENSOR_J_TYPE 2L
#undef com_phidgets_TemperatureSensorPhidget_PHIDGET_TEMPERATURE_SENSOR_E_TYPE
#define com_phidgets_TemperatureSensorPhidget_PHIDGET_TEMPERATURE_SENSOR_E_TYPE 3L
#undef com_phidgets_TemperatureSensorPhidget_PHIDGET_TEMPERATURE_SENSOR_T_TYPE
#define com_phidgets_TemperatureSensorPhidget_PHIDGET_TEMPERATURE_SENSOR_T_TYPE 4L
/*
 * Class:     com_phidgets_TemperatureSensorPhidget
 * Method:    create
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_phidgets_TemperatureSensorPhidget_create
  (JNIEnv *, jclass);

/*
 * Class:     com_phidgets_TemperatureSensorPhidget
 * Method:    getTemperatureInputCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_phidgets_TemperatureSensorPhidget_getTemperatureInputCount
  (JNIEnv *, jobject);

/*
 * Class:     com_phidgets_TemperatureSensorPhidget
 * Method:    getSensorCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_phidgets_TemperatureSensorPhidget_getSensorCount
  (JNIEnv *, jobject);

/*
 * Class:     com_phidgets_TemperatureSensorPhidget
 * Method:    getTemperature
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_com_phidgets_TemperatureSensorPhidget_getTemperature
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_phidgets_TemperatureSensorPhidget
 * Method:    getTemperatureMax
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_com_phidgets_TemperatureSensorPhidget_getTemperatureMax
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_phidgets_TemperatureSensorPhidget
 * Method:    getTemperatureMin
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_com_phidgets_TemperatureSensorPhidget_getTemperatureMin
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_phidgets_TemperatureSensorPhidget
 * Method:    getAmbientTemperature
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_com_phidgets_TemperatureSensorPhidget_getAmbientTemperature
  (JNIEnv *, jobject);

/*
 * Class:     com_phidgets_TemperatureSensorPhidget
 * Method:    getAmbientTemperatureMax
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_com_phidgets_TemperatureSensorPhidget_getAmbientTemperatureMax
  (JNIEnv *, jobject);

/*
 * Class:     com_phidgets_TemperatureSensorPhidget
 * Method:    getAmbientTemperatureMin
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_com_phidgets_TemperatureSensorPhidget_getAmbientTemperatureMin
  (JNIEnv *, jobject);

/*
 * Class:     com_phidgets_TemperatureSensorPhidget
 * Method:    getPotential
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_com_phidgets_TemperatureSensorPhidget_getPotential
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_phidgets_TemperatureSensorPhidget
 * Method:    getPotentialMax
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_com_phidgets_TemperatureSensorPhidget_getPotentialMax
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_phidgets_TemperatureSensorPhidget
 * Method:    getPotentialMin
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_com_phidgets_TemperatureSensorPhidget_getPotentialMin
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_phidgets_TemperatureSensorPhidget
 * Method:    setTemperatureChangeTrigger
 * Signature: (ID)V
 */
JNIEXPORT void JNICALL Java_com_phidgets_TemperatureSensorPhidget_setTemperatureChangeTrigger
  (JNIEnv *, jobject, jint, jdouble);

/*
 * Class:     com_phidgets_TemperatureSensorPhidget
 * Method:    getTemperatureChangeTrigger
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_com_phidgets_TemperatureSensorPhidget_getTemperatureChangeTrigger
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_phidgets_TemperatureSensorPhidget
 * Method:    getThermocoupleType
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_phidgets_TemperatureSensorPhidget_getThermocoupleType
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_phidgets_TemperatureSensorPhidget
 * Method:    setThermocoupleType
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_phidgets_TemperatureSensorPhidget_setThermocoupleType
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_phidgets_TemperatureSensorPhidget
 * Method:    enableTemperatureChangeEvents
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_phidgets_TemperatureSensorPhidget_enableTemperatureChangeEvents
  (JNIEnv *, jobject, jboolean);

#ifdef __cplusplus
}
#endif
#endif
