/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_phidgets_MotorControlPhidget */

#ifndef _Included_com_phidgets_MotorControlPhidget
#define _Included_com_phidgets_MotorControlPhidget
#ifdef __cplusplus
extern "C" {
#endif
#undef com_phidgets_MotorControlPhidget_PHIDGET_LOG_CRITICAL
#define com_phidgets_MotorControlPhidget_PHIDGET_LOG_CRITICAL 1L
#undef com_phidgets_MotorControlPhidget_PHIDGET_LOG_ERROR
#define com_phidgets_MotorControlPhidget_PHIDGET_LOG_ERROR 2L
#undef com_phidgets_MotorControlPhidget_PHIDGET_LOG_WARNING
#define com_phidgets_MotorControlPhidget_PHIDGET_LOG_WARNING 3L
#undef com_phidgets_MotorControlPhidget_PHIDGET_LOG_DEBUG
#define com_phidgets_MotorControlPhidget_PHIDGET_LOG_DEBUG 4L
#undef com_phidgets_MotorControlPhidget_PHIDGET_LOG_INFO
#define com_phidgets_MotorControlPhidget_PHIDGET_LOG_INFO 5L
#undef com_phidgets_MotorControlPhidget_PHIDGET_LOG_VERBOSE
#define com_phidgets_MotorControlPhidget_PHIDGET_LOG_VERBOSE 6L
/*
 * Class:     com_phidgets_MotorControlPhidget
 * Method:    create
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_phidgets_MotorControlPhidget_create
  (JNIEnv *, jclass);

/*
 * Class:     com_phidgets_MotorControlPhidget
 * Method:    getMotorCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_phidgets_MotorControlPhidget_getMotorCount
  (JNIEnv *, jobject);

/*
 * Class:     com_phidgets_MotorControlPhidget
 * Method:    getInputCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_phidgets_MotorControlPhidget_getInputCount
  (JNIEnv *, jobject);

/*
 * Class:     com_phidgets_MotorControlPhidget
 * Method:    getInputState
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_phidgets_MotorControlPhidget_getInputState
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_phidgets_MotorControlPhidget
 * Method:    getAcceleration
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_com_phidgets_MotorControlPhidget_getAcceleration
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_phidgets_MotorControlPhidget
 * Method:    setAcceleration
 * Signature: (ID)V
 */
JNIEXPORT void JNICALL Java_com_phidgets_MotorControlPhidget_setAcceleration
  (JNIEnv *, jobject, jint, jdouble);

/*
 * Class:     com_phidgets_MotorControlPhidget
 * Method:    getAccelerationMax
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_com_phidgets_MotorControlPhidget_getAccelerationMax
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_phidgets_MotorControlPhidget
 * Method:    getAccelerationMin
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_com_phidgets_MotorControlPhidget_getAccelerationMin
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_phidgets_MotorControlPhidget
 * Method:    getVelocity
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_com_phidgets_MotorControlPhidget_getVelocity
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_phidgets_MotorControlPhidget
 * Method:    getSpeed
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_com_phidgets_MotorControlPhidget_getSpeed
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_phidgets_MotorControlPhidget
 * Method:    setVelocity
 * Signature: (ID)V
 */
JNIEXPORT void JNICALL Java_com_phidgets_MotorControlPhidget_setVelocity
  (JNIEnv *, jobject, jint, jdouble);

/*
 * Class:     com_phidgets_MotorControlPhidget
 * Method:    setSpeed
 * Signature: (ID)V
 */
JNIEXPORT void JNICALL Java_com_phidgets_MotorControlPhidget_setSpeed
  (JNIEnv *, jobject, jint, jdouble);

/*
 * Class:     com_phidgets_MotorControlPhidget
 * Method:    getCurrent
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_com_phidgets_MotorControlPhidget_getCurrent
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_phidgets_MotorControlPhidget
 * Method:    enableMotorVelocityChangeEvents
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_phidgets_MotorControlPhidget_enableMotorVelocityChangeEvents
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_phidgets_MotorControlPhidget
 * Method:    enableCurrentChangeEvents
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_phidgets_MotorControlPhidget_enableCurrentChangeEvents
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_phidgets_MotorControlPhidget
 * Method:    enableInputChangeEvents
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_phidgets_MotorControlPhidget_enableInputChangeEvents
  (JNIEnv *, jobject, jboolean);

#ifdef __cplusplus
}
#endif
#endif
