/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_phidgets_LEDPhidget */

#ifndef _Included_com_phidgets_LEDPhidget
#define _Included_com_phidgets_LEDPhidget
#ifdef __cplusplus
extern "C" {
#endif
#undef com_phidgets_LEDPhidget_PHIDGET_LOG_CRITICAL
#define com_phidgets_LEDPhidget_PHIDGET_LOG_CRITICAL 1L
#undef com_phidgets_LEDPhidget_PHIDGET_LOG_ERROR
#define com_phidgets_LEDPhidget_PHIDGET_LOG_ERROR 2L
#undef com_phidgets_LEDPhidget_PHIDGET_LOG_WARNING
#define com_phidgets_LEDPhidget_PHIDGET_LOG_WARNING 3L
#undef com_phidgets_LEDPhidget_PHIDGET_LOG_DEBUG
#define com_phidgets_LEDPhidget_PHIDGET_LOG_DEBUG 4L
#undef com_phidgets_LEDPhidget_PHIDGET_LOG_INFO
#define com_phidgets_LEDPhidget_PHIDGET_LOG_INFO 5L
#undef com_phidgets_LEDPhidget_PHIDGET_LOG_VERBOSE
#define com_phidgets_LEDPhidget_PHIDGET_LOG_VERBOSE 6L
/*
 * Class:     com_phidgets_LEDPhidget
 * Method:    create
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_phidgets_LEDPhidget_create
  (JNIEnv *, jclass);

/*
 * Class:     com_phidgets_LEDPhidget
 * Method:    getLEDCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_phidgets_LEDPhidget_getLEDCount
  (JNIEnv *, jobject);

/*
 * Class:     com_phidgets_LEDPhidget
 * Method:    getDiscreteLED
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_phidgets_LEDPhidget_getDiscreteLED
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_phidgets_LEDPhidget
 * Method:    setDiscreteLED
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_phidgets_LEDPhidget_setDiscreteLED
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
