/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_phidgets_StepperPhidget */

#ifndef _Included_com_phidgets_StepperPhidget
#define _Included_com_phidgets_StepperPhidget
#ifdef __cplusplus
extern "C" {
#endif
#undef com_phidgets_StepperPhidget_PHIDGET_LOG_CRITICAL
#define com_phidgets_StepperPhidget_PHIDGET_LOG_CRITICAL 1L
#undef com_phidgets_StepperPhidget_PHIDGET_LOG_ERROR
#define com_phidgets_StepperPhidget_PHIDGET_LOG_ERROR 2L
#undef com_phidgets_StepperPhidget_PHIDGET_LOG_WARNING
#define com_phidgets_StepperPhidget_PHIDGET_LOG_WARNING 3L
#undef com_phidgets_StepperPhidget_PHIDGET_LOG_DEBUG
#define com_phidgets_StepperPhidget_PHIDGET_LOG_DEBUG 4L
#undef com_phidgets_StepperPhidget_PHIDGET_LOG_INFO
#define com_phidgets_StepperPhidget_PHIDGET_LOG_INFO 5L
#undef com_phidgets_StepperPhidget_PHIDGET_LOG_VERBOSE
#define com_phidgets_StepperPhidget_PHIDGET_LOG_VERBOSE 6L
/*
 * Class:     com_phidgets_StepperPhidget
 * Method:    create
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_phidgets_StepperPhidget_create
  (JNIEnv *, jclass);

/*
 * Class:     com_phidgets_StepperPhidget
 * Method:    getMotorCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_phidgets_StepperPhidget_getMotorCount
  (JNIEnv *, jobject);

/*
 * Class:     com_phidgets_StepperPhidget
 * Method:    getInputCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_phidgets_StepperPhidget_getInputCount
  (JNIEnv *, jobject);

/*
 * Class:     com_phidgets_StepperPhidget
 * Method:    getInputState
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_phidgets_StepperPhidget_getInputState
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_phidgets_StepperPhidget
 * Method:    getAcceleration
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_com_phidgets_StepperPhidget_getAcceleration
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_phidgets_StepperPhidget
 * Method:    getAccelerationMax
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_com_phidgets_StepperPhidget_getAccelerationMax
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_phidgets_StepperPhidget
 * Method:    getAccelerationMin
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_com_phidgets_StepperPhidget_getAccelerationMin
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_phidgets_StepperPhidget
 * Method:    setAcceleration
 * Signature: (ID)V
 */
JNIEXPORT void JNICALL Java_com_phidgets_StepperPhidget_setAcceleration
  (JNIEnv *, jobject, jint, jdouble);

/*
 * Class:     com_phidgets_StepperPhidget
 * Method:    getVelocity
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_com_phidgets_StepperPhidget_getVelocity
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_phidgets_StepperPhidget
 * Method:    getVelocityMax
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_com_phidgets_StepperPhidget_getVelocityMax
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_phidgets_StepperPhidget
 * Method:    getVelocityMin
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_com_phidgets_StepperPhidget_getVelocityMin
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_phidgets_StepperPhidget
 * Method:    setVelocityLimit
 * Signature: (ID)V
 */
JNIEXPORT void JNICALL Java_com_phidgets_StepperPhidget_setVelocityLimit
  (JNIEnv *, jobject, jint, jdouble);

/*
 * Class:     com_phidgets_StepperPhidget
 * Method:    getVelocityLimit
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_com_phidgets_StepperPhidget_getVelocityLimit
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_phidgets_StepperPhidget
 * Method:    getPositionMax
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_com_phidgets_StepperPhidget_getPositionMax
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_phidgets_StepperPhidget
 * Method:    getPositionMin
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_com_phidgets_StepperPhidget_getPositionMin
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_phidgets_StepperPhidget
 * Method:    setCurrentPosition
 * Signature: (IJ)V
 */
JNIEXPORT void JNICALL Java_com_phidgets_StepperPhidget_setCurrentPosition
  (JNIEnv *, jobject, jint, jlong);

/*
 * Class:     com_phidgets_StepperPhidget
 * Method:    getCurrentPosition
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_com_phidgets_StepperPhidget_getCurrentPosition
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_phidgets_StepperPhidget
 * Method:    setTargetPosition
 * Signature: (IJ)V
 */
JNIEXPORT void JNICALL Java_com_phidgets_StepperPhidget_setTargetPosition
  (JNIEnv *, jobject, jint, jlong);

/*
 * Class:     com_phidgets_StepperPhidget
 * Method:    getTargetPosition
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_com_phidgets_StepperPhidget_getTargetPosition
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_phidgets_StepperPhidget
 * Method:    getCurrent
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_com_phidgets_StepperPhidget_getCurrent
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_phidgets_StepperPhidget
 * Method:    getCurrentLimit
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_com_phidgets_StepperPhidget_getCurrentLimit
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_phidgets_StepperPhidget
 * Method:    setCurrentLimit
 * Signature: (ID)V
 */
JNIEXPORT void JNICALL Java_com_phidgets_StepperPhidget_setCurrentLimit
  (JNIEnv *, jobject, jint, jdouble);

/*
 * Class:     com_phidgets_StepperPhidget
 * Method:    getCurrentMax
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_com_phidgets_StepperPhidget_getCurrentMax
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_phidgets_StepperPhidget
 * Method:    getCurrentMin
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_com_phidgets_StepperPhidget_getCurrentMin
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_phidgets_StepperPhidget
 * Method:    setEngaged
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_com_phidgets_StepperPhidget_setEngaged
  (JNIEnv *, jobject, jint, jboolean);

/*
 * Class:     com_phidgets_StepperPhidget
 * Method:    getEngaged
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_phidgets_StepperPhidget_getEngaged
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_phidgets_StepperPhidget
 * Method:    getStopped
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_phidgets_StepperPhidget_getStopped
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_phidgets_StepperPhidget
 * Method:    enableStepperPositionChangeEvents
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_phidgets_StepperPhidget_enableStepperPositionChangeEvents
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_phidgets_StepperPhidget
 * Method:    enableStepperVelocityChangeEvents
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_phidgets_StepperPhidget_enableStepperVelocityChangeEvents
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_phidgets_StepperPhidget
 * Method:    enableCurrentChangeEvents
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_phidgets_StepperPhidget_enableCurrentChangeEvents
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_phidgets_StepperPhidget
 * Method:    enableInputChangeEvents
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_phidgets_StepperPhidget_enableInputChangeEvents
  (JNIEnv *, jobject, jboolean);

#ifdef __cplusplus
}
#endif
#endif
