/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_phidgets_EncoderPhidget */

#ifndef _Included_com_phidgets_EncoderPhidget
#define _Included_com_phidgets_EncoderPhidget
#ifdef __cplusplus
extern "C" {
#endif
#undef com_phidgets_EncoderPhidget_PHIDGET_LOG_CRITICAL
#define com_phidgets_EncoderPhidget_PHIDGET_LOG_CRITICAL 1L
#undef com_phidgets_EncoderPhidget_PHIDGET_LOG_ERROR
#define com_phidgets_EncoderPhidget_PHIDGET_LOG_ERROR 2L
#undef com_phidgets_EncoderPhidget_PHIDGET_LOG_WARNING
#define com_phidgets_EncoderPhidget_PHIDGET_LOG_WARNING 3L
#undef com_phidgets_EncoderPhidget_PHIDGET_LOG_DEBUG
#define com_phidgets_EncoderPhidget_PHIDGET_LOG_DEBUG 4L
#undef com_phidgets_EncoderPhidget_PHIDGET_LOG_INFO
#define com_phidgets_EncoderPhidget_PHIDGET_LOG_INFO 5L
#undef com_phidgets_EncoderPhidget_PHIDGET_LOG_VERBOSE
#define com_phidgets_EncoderPhidget_PHIDGET_LOG_VERBOSE 6L
/*
 * Class:     com_phidgets_EncoderPhidget
 * Method:    create
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_phidgets_EncoderPhidget_create
  (JNIEnv *, jclass);

/*
 * Class:     com_phidgets_EncoderPhidget
 * Method:    getEncoderCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_phidgets_EncoderPhidget_getEncoderCount
  (JNIEnv *, jobject);

/*
 * Class:     com_phidgets_EncoderPhidget
 * Method:    getInputCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_phidgets_EncoderPhidget_getInputCount
  (JNIEnv *, jobject);

/*
 * Class:     com_phidgets_EncoderPhidget
 * Method:    getPosition
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_phidgets_EncoderPhidget_getPosition
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_phidgets_EncoderPhidget
 * Method:    getEncoderPosition
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_phidgets_EncoderPhidget_getEncoderPosition
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_phidgets_EncoderPhidget
 * Method:    setPosition
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_phidgets_EncoderPhidget_setPosition
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_phidgets_EncoderPhidget
 * Method:    setEncoderPosition
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_phidgets_EncoderPhidget_setEncoderPosition
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_phidgets_EncoderPhidget
 * Method:    getInputState
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_phidgets_EncoderPhidget_getInputState
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_phidgets_EncoderPhidget
 * Method:    enableEncoderPositionChangeEvents
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_phidgets_EncoderPhidget_enableEncoderPositionChangeEvents
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_phidgets_EncoderPhidget
 * Method:    enableInputChangeEvents
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_phidgets_EncoderPhidget_enableInputChangeEvents
  (JNIEnv *, jobject, jboolean);

#ifdef __cplusplus
}
#endif
#endif
