/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_phidgets_PHSensorPhidget */

#ifndef _Included_com_phidgets_PHSensorPhidget
#define _Included_com_phidgets_PHSensorPhidget
#ifdef __cplusplus
extern "C" {
#endif
#undef com_phidgets_PHSensorPhidget_PHIDGET_LOG_CRITICAL
#define com_phidgets_PHSensorPhidget_PHIDGET_LOG_CRITICAL 1L
#undef com_phidgets_PHSensorPhidget_PHIDGET_LOG_ERROR
#define com_phidgets_PHSensorPhidget_PHIDGET_LOG_ERROR 2L
#undef com_phidgets_PHSensorPhidget_PHIDGET_LOG_WARNING
#define com_phidgets_PHSensorPhidget_PHIDGET_LOG_WARNING 3L
#undef com_phidgets_PHSensorPhidget_PHIDGET_LOG_DEBUG
#define com_phidgets_PHSensorPhidget_PHIDGET_LOG_DEBUG 4L
#undef com_phidgets_PHSensorPhidget_PHIDGET_LOG_INFO
#define com_phidgets_PHSensorPhidget_PHIDGET_LOG_INFO 5L
#undef com_phidgets_PHSensorPhidget_PHIDGET_LOG_VERBOSE
#define com_phidgets_PHSensorPhidget_PHIDGET_LOG_VERBOSE 6L
/*
 * Class:     com_phidgets_PHSensorPhidget
 * Method:    create
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_phidgets_PHSensorPhidget_create
  (JNIEnv *, jclass);

/*
 * Class:     com_phidgets_PHSensorPhidget
 * Method:    getPH
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_com_phidgets_PHSensorPhidget_getPH
  (JNIEnv *, jobject);

/*
 * Class:     com_phidgets_PHSensorPhidget
 * Method:    getPHMax
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_com_phidgets_PHSensorPhidget_getPHMax
  (JNIEnv *, jobject);

/*
 * Class:     com_phidgets_PHSensorPhidget
 * Method:    getPHMin
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_com_phidgets_PHSensorPhidget_getPHMin
  (JNIEnv *, jobject);

/*
 * Class:     com_phidgets_PHSensorPhidget
 * Method:    getPotential
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_com_phidgets_PHSensorPhidget_getPotential
  (JNIEnv *, jobject);

/*
 * Class:     com_phidgets_PHSensorPhidget
 * Method:    getPotentialMax
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_com_phidgets_PHSensorPhidget_getPotentialMax
  (JNIEnv *, jobject);

/*
 * Class:     com_phidgets_PHSensorPhidget
 * Method:    getPotentialMin
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_com_phidgets_PHSensorPhidget_getPotentialMin
  (JNIEnv *, jobject);

/*
 * Class:     com_phidgets_PHSensorPhidget
 * Method:    setTemperature
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_com_phidgets_PHSensorPhidget_setTemperature
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     com_phidgets_PHSensorPhidget
 * Method:    setPHChangeTrigger
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_com_phidgets_PHSensorPhidget_setPHChangeTrigger
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     com_phidgets_PHSensorPhidget
 * Method:    getPHChangeTrigger
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_com_phidgets_PHSensorPhidget_getPHChangeTrigger
  (JNIEnv *, jobject);

/*
 * Class:     com_phidgets_PHSensorPhidget
 * Method:    enablePHChangeEvents
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_phidgets_PHSensorPhidget_enablePHChangeEvents
  (JNIEnv *, jobject, jboolean);

#ifdef __cplusplus
}
#endif
#endif
