/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_phidgets_RFIDPhidget */

#ifndef _Included_com_phidgets_RFIDPhidget
#define _Included_com_phidgets_RFIDPhidget
#ifdef __cplusplus
extern "C" {
#endif
#undef com_phidgets_RFIDPhidget_PHIDGET_LOG_CRITICAL
#define com_phidgets_RFIDPhidget_PHIDGET_LOG_CRITICAL 1L
#undef com_phidgets_RFIDPhidget_PHIDGET_LOG_ERROR
#define com_phidgets_RFIDPhidget_PHIDGET_LOG_ERROR 2L
#undef com_phidgets_RFIDPhidget_PHIDGET_LOG_WARNING
#define com_phidgets_RFIDPhidget_PHIDGET_LOG_WARNING 3L
#undef com_phidgets_RFIDPhidget_PHIDGET_LOG_DEBUG
#define com_phidgets_RFIDPhidget_PHIDGET_LOG_DEBUG 4L
#undef com_phidgets_RFIDPhidget_PHIDGET_LOG_INFO
#define com_phidgets_RFIDPhidget_PHIDGET_LOG_INFO 5L
#undef com_phidgets_RFIDPhidget_PHIDGET_LOG_VERBOSE
#define com_phidgets_RFIDPhidget_PHIDGET_LOG_VERBOSE 6L
/*
 * Class:     com_phidgets_RFIDPhidget
 * Method:    create
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_phidgets_RFIDPhidget_create
  (JNIEnv *, jclass);

/*
 * Class:     com_phidgets_RFIDPhidget
 * Method:    getOutputCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_phidgets_RFIDPhidget_getOutputCount
  (JNIEnv *, jobject);

/*
 * Class:     com_phidgets_RFIDPhidget
 * Method:    getOutputState
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_phidgets_RFIDPhidget_getOutputState
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_phidgets_RFIDPhidget
 * Method:    setOutputState
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_com_phidgets_RFIDPhidget_setOutputState
  (JNIEnv *, jobject, jint, jboolean);

/*
 * Class:     com_phidgets_RFIDPhidget
 * Method:    getAntennaOn
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_phidgets_RFIDPhidget_getAntennaOn
  (JNIEnv *, jobject);

/*
 * Class:     com_phidgets_RFIDPhidget
 * Method:    setAntennaOn
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_phidgets_RFIDPhidget_setAntennaOn
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_phidgets_RFIDPhidget
 * Method:    getLEDOn
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_phidgets_RFIDPhidget_getLEDOn
  (JNIEnv *, jobject);

/*
 * Class:     com_phidgets_RFIDPhidget
 * Method:    setLEDOn
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_phidgets_RFIDPhidget_setLEDOn
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_phidgets_RFIDPhidget
 * Method:    getLastTag
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_phidgets_RFIDPhidget_getLastTag
  (JNIEnv *, jobject);

/*
 * Class:     com_phidgets_RFIDPhidget
 * Method:    getTagStatus
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_phidgets_RFIDPhidget_getTagStatus
  (JNIEnv *, jobject);

/*
 * Class:     com_phidgets_RFIDPhidget
 * Method:    enableTagGainEvents
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_phidgets_RFIDPhidget_enableTagGainEvents
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_phidgets_RFIDPhidget
 * Method:    enableTagLossEvents
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_phidgets_RFIDPhidget_enableTagLossEvents
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_phidgets_RFIDPhidget
 * Method:    enableOutputChangeEvents
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_phidgets_RFIDPhidget_enableOutputChangeEvents
  (JNIEnv *, jobject, jboolean);

#ifdef __cplusplus
}
#endif
#endif
