/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_phidgets_AccelerometerPhidget */

#ifndef _Included_com_phidgets_AccelerometerPhidget
#define _Included_com_phidgets_AccelerometerPhidget
#ifdef __cplusplus
extern "C" {
#endif
#undef com_phidgets_AccelerometerPhidget_PHIDGET_LOG_CRITICAL
#define com_phidgets_AccelerometerPhidget_PHIDGET_LOG_CRITICAL 1L
#undef com_phidgets_AccelerometerPhidget_PHIDGET_LOG_ERROR
#define com_phidgets_AccelerometerPhidget_PHIDGET_LOG_ERROR 2L
#undef com_phidgets_AccelerometerPhidget_PHIDGET_LOG_WARNING
#define com_phidgets_AccelerometerPhidget_PHIDGET_LOG_WARNING 3L
#undef com_phidgets_AccelerometerPhidget_PHIDGET_LOG_DEBUG
#define com_phidgets_AccelerometerPhidget_PHIDGET_LOG_DEBUG 4L
#undef com_phidgets_AccelerometerPhidget_PHIDGET_LOG_INFO
#define com_phidgets_AccelerometerPhidget_PHIDGET_LOG_INFO 5L
#undef com_phidgets_AccelerometerPhidget_PHIDGET_LOG_VERBOSE
#define com_phidgets_AccelerometerPhidget_PHIDGET_LOG_VERBOSE 6L
/*
 * Class:     com_phidgets_AccelerometerPhidget
 * Method:    create
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_phidgets_AccelerometerPhidget_create
  (JNIEnv *, jclass);

/*
 * Class:     com_phidgets_AccelerometerPhidget
 * Method:    getAxisCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_phidgets_AccelerometerPhidget_getAxisCount
  (JNIEnv *, jobject);

/*
 * Class:     com_phidgets_AccelerometerPhidget
 * Method:    getAccelerationMax
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_com_phidgets_AccelerometerPhidget_getAccelerationMax
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_phidgets_AccelerometerPhidget
 * Method:    getAccelerationMin
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_com_phidgets_AccelerometerPhidget_getAccelerationMin
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_phidgets_AccelerometerPhidget
 * Method:    getAcceleration
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_com_phidgets_AccelerometerPhidget_getAcceleration
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_phidgets_AccelerometerPhidget
 * Method:    setAccelerationChangeTrigger
 * Signature: (ID)V
 */
JNIEXPORT void JNICALL Java_com_phidgets_AccelerometerPhidget_setAccelerationChangeTrigger
  (JNIEnv *, jobject, jint, jdouble);

/*
 * Class:     com_phidgets_AccelerometerPhidget
 * Method:    getAccelerationChangeTrigger
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_com_phidgets_AccelerometerPhidget_getAccelerationChangeTrigger
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_phidgets_AccelerometerPhidget
 * Method:    enableAccelerationChangeEvents
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_phidgets_AccelerometerPhidget_enableAccelerationChangeEvents
  (JNIEnv *, jobject, jboolean);

#ifdef __cplusplus
}
#endif
#endif
